관리자 페이지
EveryUniv/student-council-homepage-backend pull request #294
Opened 2023-04-22 17:32 UTC by YOONSEOUNGHWAN

## 관리자 페이지
관리자 페이지는 /manage 경로로 사용합니다. *해당 부분은 NginX에서 /api 를 제외해야 할 것 같습니다*

**관리자 페이지 로직은 Application의 Service 코드를 종속하지 않습니다.**
- 이렇게 작성한 이유는 서비스 로직과 관리자 페이지의 종속을 피하기 위함입니다.
- 관리자 페이지는 Repository를 종속하고 있습니다.
- 따로 관리자 로그인 페이지를 만들지 않았습니다. -> Admin 계정으로 Login 한 뒤, /manage로 접근하면 됩니다.  *로그인 페이지가 필요하다면만들겠습니다*

## Main Page
<img width="575" alt="image" src="https://user-images.githubusercontent.com/78069223/233798150-a6a7973c-02e2-496b-b0cb-e993ba4a2475.png">

## User Page
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/78069223/233798190-96f2022e-9ae3-43a5-8716-62e832df6be7.png">

## Post Page
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/78069223/233798210-8ed40e7b-202d-4ac0-b636-1e9f8a06130e.png">

## Tag Page
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/78069223/233798230-58771cba-1547-4965-874e-01cc32ab55a5.png">

## Rental Page
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/78069223/233798253-a78ef05f-5d3f-40cc-b1f5-263548177f83.png">

## Rental Item Page
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/78069223/233798274-cd1aaa48-aa7b-4dff-b600-20669863d7e1.png">

2023-04-23 04:27 UTC, won983212 requested changes
`Controller`는 가능한 `Repository`가 아닌 `Service`를 의존해야합니다.

Spring에서 사용하는 Controller, Service, Repository 패턴은 Layered Architecture의 한 종류입니다. 이 설계 방식에서는 바로 아래 층간 의존성만 존재합니다. (Controller -> Service -> Repository)

![image](https://user-images.githubusercontent.com/1351461/233819217-6d26139a-b496-472f-9e51-0d6df5494889.png)

이렇게 설계하는 이유는
1. 결합도를 최대한 줄이기 위함입니다. 예를 들어 층간 경계를 뛰어 넘어서 Controller가 Service대신 Repository를 의존한다면, 프로젝트 전체적으로 Repository의 의존도가 더 높아집니다.
2. 역할을 철저하게 구분하기 위해서입니다. Controller는 적절히 요청을 받아 Service로 넘기는 IO개념의 역할입니다. 그래서 비즈니스 로직이 최대한 들어가면 안됩니다. 극단적으로는 Service와 Repository만으로도 앱이 돌아가야합니다. Controller는 딱 요청과 응답의 중계만 담당하는 것이 좋습니다.
3. 변경 전파를 최소화하기 위해서입니다. (캡슐화와 응집도와 관련) Service가 Repository보다 상위 컴포넌트입니다. Service에서 Repository를 활용해서 비즈니스 로직을 처리합니다. Repository는 가급적 Service단에서만 사용해야합니다. 캡슐화와 유사합니다. Tag로 예를 들어보면, Tag 이름을 update하는 로직은 repository에서 tag를 가져와 이름을 update하는 방식으로 이루어집니다. 이 과정은 Service에서 처리하고, 그 외의 레벨에서는 과정 자체를 몰라야합니다. (추상화) 이렇게 해야 응집도가 올라가고, 결과적으로 유지보수하기 편해집니다.
4. 모델 의존성을 줄이기 위해서입니다. Repository를 사용하면 필연적으로 Entity를 의존하게 됩니다. Controller에서는 Entity를 직접 사용하기보다 Service에서 변환해주는 것이 좋습니다. 가능한 Entity를 더 적은 레벨에 전파하는 것입니다. 물론 이 경우는 서버에서 직접 페이지를 렌더링하므로 dto를 사용하지않아 큰 문제는 없겠지만, 기본적으로 layer별로 dto를 나누는 것이 이상적입니다. (현재 프로젝트에서는 이상과 타협해서 Controller, Service에서는 같은 dto를 사용하고 service, repository만 entity를 사용합니다.)

2023-04-23 04:27 UTC, won983212 commented on src/main/java/com/dku/council/admin/page/CommentPageController.java
> +        Comment comment = commentRepository.findById(commentId).get();
Controller는 로직을 포함하지 않는 설계가 좋습니다.

2023-04-23 14:24 UTC, YOONSEOUNGHWAN commented
## 피드백 반영
- Controller 는 Service 를 의존합니다
- 데이터 바인딩에 필요한 정보는 dto 패키지에 담아두었습니다.

## Banner Page
- 배너 페이지는 최신 등록순으로 랜더링 됩니다.
- 순서를 바꾸고자 할 경우, 추가/삭제를 활용합니다.
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/78069223/233845414-f175357c-17fa-42f3-9685-803cff3d4154.png">

2023-04-24 01:29 UTC, won983212 approved these changes
사소한 리팩토링은 나중에 하겠습니다. 고생하셨습니다 :)

2023-04-24 01:29 UTC, won983212 commented on src/main/java/com/dku/council/admin/page/service/PostPageService.java
> +    public Page<PostPageDto> list(String keyword, String type, String status, Pageable pageable){
※ 향후 개선이 필요한 부분입니다

2023-04-24 01:29 UTC, merged