관리자 귀향버스 생성, 수정, 삭제
EveryUniv/student-council-homepage-backend pull request #411
Opened 2023-07-03 14:54 UTC by YOONSEOUNGHWAN

## 관리자 페이지에서 필요한 service를 구현하였습니다.

**귀향버스 수정 로직은 Caching 된 잔여석에 의존합니다 -> 추후 update 예정**

### TODO
- [ ] test code 작성

2023-07-03 23:40 UTC, won983212 requested changes
추가로 나중에 테스트 작성하실 때 정상작동 테스트보다 실패 테스트에 더 중점을 두고 작성해주시면 좋을 것 같아요.

ex) "티켓이 이미 발급된 경우 버스를 삭제할 수 없는지?" 등 예외를 잘 handling하는지 테스트

2023-07-03 23:40 UTC, won983212 commented on src/main/java/com/dku/council/domain/admin/dto/request/RequestCreateHomeBusDto.java
> +    private final String label;
가독성을 위해 필드에 줄바꿈 한번씩만 넣어주세요!

2023-07-03 23:40 UTC, won983212 commented on src/main/java/com/dku/council/domain/admin/service/HomeBusPageService.java
> +        Optional<HomeBusTicket> optionalHomeBusTicket = homeBusTicketRepository.findByBusId(id);
한 버스에 대해 여러명이 티켓을 발급하면 이 부분에 오류가 발생할 수 있을 것 같습니다.
Optional대신 list로 받고 isEmpty인지 확인하는게 더 안전할 것 같아요!

2023-07-04 02:08 UTC, YOONSEOUNGHWAN commented on src/main/java/com/dku/council/domain/admin/dto/request/RequestCreateHomeBusDto.java
> +    private final String label;
넵 알겠습니다!

2023-07-04 02:09 UTC, YOONSEOUNGHWAN commented on src/main/java/com/dku/council/domain/admin/service/HomeBusPageService.java
> +        Optional<HomeBusTicket> optionalHomeBusTicket = homeBusTicketRepository.findByBusId(id);
맞습니다 ^.^
수정하겠습니다~! 감사합니다.

2023-07-04 06:38 UTC, won983212 approved these changes

2023-07-05 07:22 UTC, merged